data_config:
  #H_G: \image\distance \mask\distance_mask 480 x 496
  dataset_dir: ../../Datasets/ZY_0310/data
  txt_dir: data/zy

train_config:
  epochs: 100
  batch_size: 2
  learning_rate: 0.0001
  txt_path: data/zy
  output_dir: outputs/zy
  iterations: 10
  seed: 1234

net_config:
  n_classes: 2

